# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 994fd1e430fdace3c6a1b4fa716180b26b9d1d27192946d9508c2ac592054b7909da379bd1b18aafa12929b96f1c9930f793977619dcea97efbea28e52468555

test:
  secret_key_base: 1cc256357f6ad03058caacf268c9399f85e7eee834b5e113443e33dffa920d9d9bc70b93392378852a98d319cd560a12b3828efe72a0df3dd63ac3f878579778

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
